Repository grafbase/pathfinder, pull requests merged in 2023-10, with the labels that each got.

#67 CI - First version for macOS
  .github/workflows/ci.yml
  apps/desktop/package.json
  apps/desktop/src-tauri/Cargo.lock
  apps/desktop/src-tauri/Cargo.toml
  apps/desktop/src-tauri/tauri.conf.json
Labels: ci, release

#97 GitHub action
  .github/workflows/ci.yml
Labels: release

#93 Gb 4992 send application/json content type by default
  packages/core/src/components/connect/connect.css.ts
  packages/core/src/components/connect/connect.tsx
  packages/core/src/components/http-header-control/components--http-header-control.stories.tsx
  packages/core/src/components/http-header-control/http-header-control.css.ts
  packages/core/src/components/http-header-control/http-header-control.tsx
  packages/core/src/components/scout-tools/scout-tools.tsx
  packages/core/src/trailblazer/trailblazer.stories.tsx
  packages/stores/src/session-store/actions/init-session.ts
  packages/stores/src/session-store/slices/http-headers/http-headers-state.ts
Labels: enhancement, desktop app

#121 Add Windows desktop app builds
  .github/workflows/ci.yml
  apps/desktop/package.json
  apps/desktop/src-tauri/Cargo.toml
  apps/desktop/src-tauri/tauri.conf.json
Labels: release

#123 Refactor schema documentation component to accept schema as prop
  .changeset/late-drinks-look.md
  packages/react/src/ide/ide.tsx
  packages/react/src/index.ts
  packages/react/src/schema-documentation/components/schema-documentation/schema-documentation.tsx
  packages/react/src/schema-documentation/schema-documentation.stories.tsx
  packages/react/src/schema-view/schema-view.stories.tsx
  packages/react/src/schema-view/schema-view.tsx
Labels: enhancement, react-component

#130 Fix schema polling
  .changeset/shy-hairs-repair.md
  apps/desktop/package.json
  apps/desktop/src/components/app/app.tsx
  examples/nextjs-example/.eslintrc.json
  examples/nextjs-example/package.json
  examples/nextjs-example/src/app/page.tsx
  packages/react/src/ide/ide.css.ts
  packages/react/src/ide/ide.tsx
  packages/react/src/pathfinder/pathfinder.stories.tsx
  packages/react/src/pathfinder/pathfinder.test.tsx
  packages/react/src/pathfinder/pathfinder.tsx
  packages/react/src/pathfinder/pathfinder.types.ts
  packages/stores/src/schema-store/actions/do-schema-polling.ts
  packages/stores/src/schema-store/actions/load-schema.ts
  packages/stores/src/schema-store/actions/reset-schema-polling.ts
  packages/stores/src/schema-store/actions/set-schema-polling-timer.ts
  packages/stores/src/schema-store/schema-store.types.ts
  packages/stores/src/schema-store/state.ts
  packages/stores/src/session-store/slices/http-headers/index.ts
  pnpm-lock.yaml
Labels: desktop app, react-component

#156 release 0.1.4
  apps/desktop/package.json
  apps/desktop/src-tauri/Cargo.toml
  apps/desktop/src-tauri/tauri.conf.json
  apps/website/src/components/DownloadButton.tsx
Labels: release

#168 desktop app 0.1.5 release
  apps/desktop/package.json
  apps/desktop/src-tauri/Cargo.toml
  apps/desktop/src-tauri/tauri.conf.json
Labels: desktop app, release

#169 pathfinder.dev: update mac download version and fix typescript
  apps/website/src/components/DownloadButton.tsx
Labels: pathfinder.dev
